### ISSUE TITLE
Add link to rubyburger shop

### ISSUE THREAD

**Issue by borisrorsvort** [brug-be/rubybelgium#14]
Is that still orderable ? 
if yes add it to website :) 

https://rubyburgers.spreadshirt.be/men-s-hoodie-A26158598/customize/color/446

**Comment by otagi** [comment]
Should we create a new Shopping section? :)

**Comment by borisrorsvort** [comment]
More like Goodies i'd say. It can also be a source a revenue for the association :)

**Comment by otagi** [comment]
Are there goodies for the other RubyBelgium "brands"?

**Comment by borisrorsvort** [comment]
once we have a logo I guess yes :)

**Comment by borisrorsvort** [comment]
According to @toch, we'd better do a group order regularly. Christophe know a shop that has interesting prices

**Comment by borisrorsvort** [comment]
Ok ill prepare a design then
