### ISSUE TITLE
The Ruby Belgium logo

### ISSUE THREAD

**Issue by borisrorsvort** [brug-be/rubybelgium#15]
I've been doodling a bit this weekend. What do you think about this one? 
Constructive feedback very welcome. Try to model your thoughts around some vital logo aspects as I tried to follow and listed below:

* Simple
* Memorable
* Timeless
* Versatile (small version included visualize better for the shrink test)
* Appropriate

More info at http://justcreative.com/2009/07/27/what-makes-a-good-logo

### V1.1

![logo 2](https://cloud.githubusercontent.com/assets/39081/11467777/b971f2fa-974a-11e5-8452-902c8a049189.png)

![logo_bw](https://cloud.githubusercontent.com/assets/39081/11484235/3a0cd92c-97ad-11e5-8839-b88d3ff40e1f.png)

Nathan's version:

![](https://cloud.githubusercontent.com/assets/8747231/11503003/85c3a26a-983e-11e5-8738-6907fa25a4fd.png)

**Comment by apneadiving** [comment]
Its beautiful, for sure. But... you told me its linked to the atomium but I wouldnt have guessed and as a frenchie, I didnt know the atomium before arriving in bxl, so the symbol is not that obvious to me

**Comment by borisrorsvort** [comment]
Eheh true. The real question would be to know if we actually want an obvious reference to it or not. ;)
Honestly I'm not sure I'm capable of making it more obvious without it to be too kitch ^^ 
For sure it got some balls at least :stuck_out_tongue:

**Comment by joren** [comment]
looks pretty good :+1: I like it!

**Comment by otagi** [comment]
Balls are a good national symbol actually. Belgium is full of them: atom balls, [boulets](https://fr.wikipedia.org/wiki/Boulet_à_la_liégeoise), [smoutebollen](http://www.flanderstoday.eu/living/bite-smoutebollen), ... :stuck_out_tongue: 

I like the connected dots idea. It also symbolizes the connection between people, which goes well with the website's slogan "The association is more about the people than the technology".

The tiny logo version looks a little bit crowded, as the dots are less evenly spaced. How about removing the inner dots for that one?

The ruby red looks great. As an easter-eggy alternative, I used the [Belgian flag red](https://en.wikipedia.org/wiki/Flag_of_Belgium#Design_and_specifications) for the [website](http://rubybelgium.be).

**Comment by otagi** [comment]
@apneadiving: I don't think the symbols _have_ to be obvious at first sight. Think about the arrow in the FedEx logo, or the Turing reference in Apple's one.

The bullet points that Boris highlighted are what should be immediately obvious, IMHO. Symbols are important, but come second place in the process.

**Comment by borisrorsvort** [comment]
I have updated the logo to a new version.

### changelog:

* Bigger balls for the big logo
* less balls for the small one to declutter it a bit

**Comment by hannesfostie** [comment]
Considering how tiny the small one is, it's actually fairly clear. Good job! Did you pixelhint that at all?

**Comment by borisrorsvort** [comment]
Nope. I'll wait to see if the board decides it's good first.

**Comment by borisrorsvort** [comment]
@toch any thoughts ?

**Comment by hannesfostie** [comment]
I like it a lot. A little bit of pixelhinting will make it even better at the small size which is already quite awesome. Good stuff!

**Comment by toch** [comment]
@borisrorsvort I also like it :) especially the simplicity. Could you try with the red that @otagi has suggested?

How does it look like in bw?

**Comment by borisrorsvort** [comment]
No so fond of the red of the Belgian flag for large areas, as very vivid background colors make letters and shapes smaller, blurry & vibrating, ... 

I've put a bw version

**Comment by otagi** [comment]
Fair point for the Belgian red. In the website's case, though, I feel its flashiness brings some energy.

The next challenge then: how and where would we use the logo on the website? (having 2 different reds at the same time might weaken the graphic identity)

PS: The B/W version works quite well.

**Comment by 10toNathan** [comment]
Looks cool @borisrorsvort
But I can't really see the connection to Belgium in it.
The resemblance to the official Ruby logo is a bit big on this one, don't you think?

**Comment by borisrorsvort** [comment]
I'd say it rather a good thing :)

**Comment by 10toNathan** [comment]
These were my logo ideas
(not saying these are better, just throwing them out here)

![logo-ideas-02](https://cloud.githubusercontent.com/assets/8747231/11503003/85c3a26a-983e-11e5-8738-6907fa25a4fd.png)

**Comment by borisrorsvort** [comment]
Thanks for adding them. I'll add them to the description

**Comment by toch** [comment]
thanks @10toNathan for sharing your work

**Comment by nicefiction** [comment]
Great logo (V1.1) Boris. I like the simplicity and how it suggests 'networking'.

**Comment by nicefiction** [comment]
Here's a version with warmer colours. I've also made the balls slightly (115%) larger:

![rubybelgium-01](https://cloud.githubusercontent.com/assets/6013199/11586500/be191fc8-9a73-11e5-82bf-45e6854010a2.jpg)

Colour guide:
1. Balls: R224 G163 B163
2. Lines: R204 G102 B102
3. text: R233 G210 B210, font: Futura Medium

**Comment by nicefiction** [comment]
Here's a more playful version with coloured balls and a little wordplay:

![rube-02-01](https://cloud.githubusercontent.com/assets/6013199/11586668/fde6d48c-9a74-11e5-8f98-23a6251417e4.jpg)

Note: Apparently 'rube' is an informal American noun for a 'country bumpkin'. A 'bumpkin' is an 'unsophisticated or socially awkward person from the countryside'. I guess you'd pronounce 'rube' and RuBE' differently? :)

**Comment by nicefiction** [comment]
<%= I just realised that RuBE is also a play on 'ERB' %>

;)

**Comment by nicefiction** [comment]
Warning: The current v1.1 logo does not scale down very well. There's too much detail that gets lost. You will need to simplify the logo to make it work. This is done by reducing the concept of the logo to its bare essentials:

![rube_small-01](https://cloud.githubusercontent.com/assets/6013199/11588438/f4744ce8-9a80-11e5-9f1d-68a630254fd9.jpg)

**Comment by toch** [comment]
Thanks @nicefiction for the suggestions.

Why not having the full versions with many dots, and the small version with one big dot?

For the name, I don't like `RuBE`, more over the name of the association is `Ruby Belgium`.

**Comment by nicefiction** [comment]
That's the idea: Have a detailed big version with the many dots && a simplified small version with one dot.

No worries about the name. I am okay with Ruby Belgium as well.

**Comment by toch** [comment]
By the way, I forgot that the play with Belgian colors is a nice idea.

**Comment by borisrorsvort** [comment]
I don't like rube either. I'll try again to declutter the small version. 
I'm thinking about just keeping the dots but removing the line. 
For the font I've used Montserrat. I don't recommend using Futura as this is a very old font and kind of overused.

**Comment by nicefiction** [comment]
@borisrorsvort , I could send you the original Adobe Illustrator files for you to work from.

**Comment by nicefiction** [comment]
@borisrorsvort , I hope you don't mind me refining your concept. I thought it was a strong starting point.

**Comment by nicefiction** [comment]
@borisrorsvort , I am not a big fan of Montserrat as it has many hooks and not much distinction between capitals and regulars.

**Comment by borisrorsvort** [comment]
Honestly, I'd rather let people vote on several solutions rather than making a chimera of all different ideas. This will go much faster.
Feedback its still appreciated though. But let's keep the three versions separated.

**Comment by nicefiction** [comment]
@borisrorsvort , Okay. Anyway, I am in favour of your proposal. With warmer colours.

**Comment by toch** [comment]
@borisrorsvort @10toNathan @nicefiction have you updated versions, or may I consider the current ones as the last?

**Comment by borisrorsvort** [comment]
There will be some small re-adjustement but thats the last version.

**Comment by borisrorsvort** [comment]
Final version round

![black inline copy](https://cloud.githubusercontent.com/assets/39081/12792146/c12fbcf0-caaa-11e5-9952-25e349bf6185.png)
![black stacked copy](https://cloud.githubusercontent.com/assets/39081/12792145/c12feed2-caaa-11e5-9a7e-2349d8af3805.png)
![black inline](https://cloud.githubusercontent.com/assets/39081/12792148/c1478a6a-caaa-11e5-9add-2a012ed38bf7.png)
![black stacked](https://cloud.githubusercontent.com/assets/39081/12792147/c1477bce-caaa-11e5-87fb-2329415db7a0.png)
![red inline](https://cloud.githubusercontent.com/assets/39081/12792149/c14e1966-caaa-11e5-970d-be03ca13ed78.png)
![red stacked](https://cloud.githubusercontent.com/assets/39081/12792150/c152d92e-caaa-11e5-9b04-290441551b51.png)
