### ISSUE TITLE
Improve the contrast of logo and banner text by applying darker bg with opacity

### ISSUE THREAD

**Issue by borisrorsvort** [brug-be/rubybelgium#2]

**Comment by otagi** [comment]
Good idea. I'd wait until we've selected the definitive background image, though. (it's using random images from lorempixel.com for now.)

**Comment by borisrorsvort** [comment]
:+1:

**Comment by otagi** [comment]
I [added](https://github.com/otagi/rubybelgium/commit/6792ee00d176b5ca4a8a667fb28a43b81467e927) `text-shadow` to the nav and header text, to improve readability. Not totally satisfied with the [result](http://otagi.github.io/rubybelgium). Should we try a darker background instead?

**Comment by toch** [comment]
5ef0d9ddda9e48e4316d6fd492833ca02e53d404 fixes that I think. If ok for you I'll close the issue.

**Comment by otagi** [comment]
Thanks @toch for the patch. Closing this one.
