### ISSUE TITLE
Is the Brug website still relevant?

### ISSUE THREAD

**Issue by borisrorsvort** [brug-be/rubybelgium#26]
If not what info get we get back from it and what can we do with it?
What would be the steps to take it down?

**Comment by borisrorsvort** [comment]
@toch  ?

**Comment by toch** [comment]
i'm not alone on this. cf @otagi and board.

As we have the meetup, it could be irrelevant, and/or maybe just a page on the main website is enough.

IF we start to have a lot of content, regular amazing lineup, videos and so on, it could be useful.

@otagi what are your thoughts?

**Comment by otagi** [comment]
The last news on brug.be is from 2013. It doesn't reflect the current group's vibrancy. So we should at least rework the page. Or redirect the domain to a rubybelgium.be page. It may have more visibility with the latter solution.

@toch: Do you have visitors stats for brug.be? And would you like to keep using the domain name?

**Comment by borisrorsvort** [comment]
Biggest problem for is that it appears before the current official site
![image](https://cloud.githubusercontent.com/assets/39081/13739375/2424b646-e9cb-11e5-951a-d1d3884a7e72.png)

And thats misleading

**Comment by toch** [comment]
@borisrorsvort what are the keywords you used for the search?

I suggest the following:

* add a page on the main website dedicated to BRUG (with a link to the meetup, who organizes it, how to sponsor it, the coming events)
* redirect brug.be to that page

**Comment by borisrorsvort** [comment]
I used "Ruby belgium".
Good idea for the separate page. 
Maybe we alrady need an "Activities" dropdown menu
