### ISSUE TITLE
Press section

### ISSUE THREAD

**Issue by otagi** [brug-be/rubybelgium#27]
There has been some talks about being more proactive with the press, to gain coverage and visibility.

In that spirit, a dedicated Press page would be a good addition. Some examples:

- [RailsGirls](http://railsgirls.com/press)
- [GitHub](https://github.com/about/press)
- [AirBnb](https://www.airbnb.com/press/news)
- [Kickstarter](https://www.kickstarter.com/press)

**Comment by borisrorsvort** [comment]
Im thinking that extraction the contact block to its own page could be a start. There we could gather contact infos foe each of the activities we organize. 
Other idea is to gather a list of link to articles about us but not sure we have so many to show at the present time

**Comment by toch** [comment]
I like the idea, but please discuss it with the board as it concerns public vitrine of the association.

Anyway, at first keep it simple and then iterate ;).

**Comment by dantesolis** [comment]
Hey  guys I'll be taking care of this issue. Should I start with the `Contact page` or the `Press Page` or no preference?

**Comment by borisrorsvort** [comment]
@dantesolis  When I design a page I always start with the content. So you can start thinking about these questions:

* Is there a reason we should have a separate contact and press page.
* If yes what would be the content / purpose of each
* If not what would the hierarchy of info on the page. (What do I see & What do I do)
* What info do we have now vs what's missing
* What the smaller implementation of it we can do to achieve the goal

Big thanks already ! 😄

**Comment by dantesolis** [comment]
@borisrorsvort, thanks for the pointers, have to admit that it helps me streamline the whole process, instead of anting to do everything in one sitting and then failing. .

**Comment by borisrorsvort** [comment]
@dantesolis Any news ?

**Comment by dantesolis** [comment]
Hey @borisrorsvort, I'm trying to pull my local changes to here, but I keep getting a  
```remote: Permission to brug-be/rubybelgium.git denied to dantesolis.
fatal: unable to access 'https://github.com/brug-be/rubybelgium.git/': The requested URL returned error: 403```
error?

**Comment by otagi** [comment]
@dantesolis Did you clone this repository, or your own fork? The latter is the recommended method for this project. (See [the README Contributing section](https://github.com/brug-be/rubybelgium/blob/master/README.md#contributing))

**Comment by dantesolis** [comment]
@otagi I had  originally clone it, but that wasn't working when pushing it, so  went ahead and cloned my fork and change the remotes. That solved it. Thanks by the way

**Comment by borisrorsvort** [comment]
@toch I have discussed on slack with @dantesolis and told him I should have have clearer on the ticket about what I was expecting. I think these questions should be answered before immplemention:

* Is there a reason we should have a separate contact and press page.
* If yes what would be the content / purpose of each
* If not what would the hierarchy of info on the page. (What do I see & What do I do)
* What info do we have now vs what's missing
* What the smaller implementation of it we can do to achieve the goal

As a first step I have asked @dantesolis to start collecting some press articles we might already have to see we we can do with them.

I also believe that by the time we figure out the site we'll be out in its first version, hence my earlier comments

**Comment by toch** [comment]
> Is there a reason we should have a separate contact and press page.

for now, I don't think so as we do not have real materials to put there. the contact can stay at the end of the page for me

> If yes what would be the content / purpose of each

contact: gather the contact details (how to contact us, bank account details)

> If not what would the hierarchy of info on the page. (What do I see & What do I do)
> What info do we have now vs what's missing

the bank account is missing

> What the smaller implementation of it we can do to achieve the goal

the current one :)
