### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by otagi** [brug-be/rubybelgium#29]
We currently don't have any analytics for the site. 

The easiest / most popular is of course Google.

[Piwik](https://github.com/piwik/piwik) is an open source (sorry Richard, _Libre_) alternative. It's PHP / MySQL, so it needs a little more install work, and a server.

**Comment by borisrorsvort** [comment]
@otagi Can I suggest we start with https://elements.heroku.com/buttons/edukorg/heroku-docker-piwik ?
Lets create an rubybelgium heroku account.
@toch We do we keep the credentials for the org services ?

**Comment by toch** [comment]
I'd like the following answered first: why do you want metrics? what's the priority?

@borisrorsvort we don't for now, this is really a headache, that's why I'd like to keep it simple as much as possible.

**Comment by otagi** [comment]
> why do you want metrics? what's the priority?

Not a priority. It's just nice to know if we get 1 or 1000 visitors, what does (not) work on the pages, etc.

**Comment by borisrorsvort** [comment]
We'll as we doing much of new stuff to the website, I'd like to see if people see it.
I'd like to see what the channels are also. For example where is our traffic coming from.
Why? so we can improve where we suck and do more of where we're good at.

Ex: 
- Traffic coming from facebook/twitter post or organic.
- for organic, what are the top referer. In case of a newspaper article, we can see which media channels bring the most trafic.
- If we do more of the job thing, would be nice to see it has some impact
- What is the bounce rate on most pages to see which one we need to improve
... many more

**Comment by hannesfostie** [comment]
I'd suggest just going with google analytics... but if you go for something like piwik above, pm me in slack before you make a brug account just for that one app ;-)

**Comment by borisrorsvort** [comment]
Ok but we still do need a google account then ^^ Also gonna be used if we start doing this google form for the salaries. @toch Any concerns for using google for now ?

**Comment by toch** [comment]
@borisrorsvort  we are using gapps for association, so we're set up to have an account linked to the association.

**Comment by otagi** [comment]
I can setup the website for Google Analytics if you provide me the Google tracking ID, or an access to the association's Analytics account.

**Comment by borisrorsvort** [comment]
https://github.com/brug-be/rubybelgium/pull/39
