### ISSUE TITLE
Performance issue with webfonts

### ISSUE THREAD

**Issue by flexbox** [brug-be/rubybelgium#3]
```
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
<link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
```

I think we don't need all these ?

**Comment by otagi** [comment]
I agree, it's too much. (It was the Agency template's default.)
I could revert to plain old Helvetica, but... 
If someone with better typographic expertise than me wants to tweak this part, the light is green. ;-)

**Comment by otagi** [comment]
As an aside, it seems that webfonts might be content-blocked in the future.

Exhibit A: Peace, a content blocker for iOS 9, has an option to disable them:
http://www.marco.org/2015/09/16/peace-content-blocker

**Comment by otagi** [comment]
Monserrat is not used anymore, AFAIK. So we should remove the link.

@borisrorsvort Would you like to keep using Kaushan, Droid, and Roboto for the current design?

**Comment by borisrorsvort** [comment]
For me 2 fonts is a maximum. Ill try two review the situation and make a proposal asap
