### ISSUE TITLE
Add a Ruby salaries section

### ISSUE THREAD

**Issue by borisrorsvort** [brug-be/rubybelgium#30]
As baby step I suggest we copy the same structure as uxBelgium
http://uxdesignin.be/salaries
A page that renders live data from a google form
We can ask almost the same questions.
I suggest, as they did, to exclude freelancers for now, though we can add them in the rubshops section as uxbelgium did too. http://uxdesignin.be/

![designer_salaries_survey__ux_designers_in_belgium_2016-03-17_15-49-28](https://cloud.githubusercontent.com/assets/39081/13849781/e25b0d48-ec57-11e5-84d1-e8cfc6a5d984.png)

I can suggest the following categories:

- Front-end developer
- Back-end developer
- Full stack developer
- Other

Tech suggestion:

* graph.js http://www.chartjs.org/docs/

Todos:

- [x] Make a Jobs dropdown with Available jobs, Ruby salaries, Ruby shops
- [x] Design the page (with link to the survey form, explanatory text, mulitple sections, ...)
- [x] Add the graphs

**Comment by borisrorsvort** [comment]
The survey is ready and will be launched soon, So we need to wait until we have enough answers before implementing the dataviz.

**Comment by borisrorsvort** [comment]
The board decided to let it run for another 2 weeks. But someone can take this on after https://github.com/brug-be/rubybelgium/pull/54 has been merged

**Comment by ys** [comment]
Is there a link here for the survey?

**Comment by borisrorsvort** [comment]
@ys  The results or the form?

**Comment by ys** [comment]
to the form

**Comment by borisrorsvort** [comment]
@ys herre you go http://goo.gl/forms/wtpQBz7UywxqWHHk1
