### ISSUE TITLE
Update banner on social media sites

### ISSUE THREAD

**Issue by borisrorsvort** [brug-be/rubybelgium#31]
Found a nice tool to crop them if you have a base image.
I'll provide the images. Someone need to upload them (except for facebook where i have access)

http://www.autreplanete.com/ap-social-media-image-maker/

- [x] Facebook
- [x] Twitter
- [x] Meetup

**Comment by otagi** [comment]
Any advantages over a simple Preview.app crop / resize?

**Comment by borisrorsvort** [comment]
it knows the right sizes :)

**Comment by otagi** [comment]
Fair enough! :)

Automator (as a service or droplet) could also be used to automate this.

**Comment by borisrorsvort** [comment]
Its a one shot, not sure it worth it

**Comment by otagi** [comment]
@borisrorsvort Can you provide an updated banner image for Twitter? I'll update it on the account.

**Comment by borisrorsvort** [comment]
![twitter](https://cloud.githubusercontent.com/assets/39081/14404484/d95712f0-fe77-11e5-9489-ff1559ca5062.jpg)

**Comment by borisrorsvort** [comment]
![twitter](https://cloud.githubusercontent.com/assets/39081/14404488/e5241e66-fe77-11e5-8cc2-99a1333ca051.jpg)

**Comment by otagi** [comment]
It's [online](https://twitter.com/rubybelgium).
