### ISSUE TITLE
Gent and Ghent are the same city

### ISSUE THREAD

**Issue by lienvdsteen** [brug-be/rubybelgium#32]
see http://grab.by/P6lq
Ghent is just english for Gent. Just creating this issue so I'll remember to update this.

**Comment by otagi** [comment]
Which spelling do you favor, for general RubyBelgium communications?

**Comment by lienvdsteen** [comment]
I guess if we're doing English we can go for _Ghent_ as we go for _Brussels_ too, right?

**Comment by borisrorsvort** [comment]
Done https://github.com/brug-be/rubyshops/commit/0f7d3d358ceb49358fefc705ef5eb6805f551a1f
