### ISSUE TITLE
Add coding guideline in contribution

### ISSUE THREAD

**Issue by borisrorsvort** [brug-be/rubybelgium#43]

**Comment by toch** [comment]
I think we need the following

* coding guidelines for
  * Stylesheets CSS
  * JS
  * Ruby and Middleman
* how to run locally middleman
* which color palette to use, which fonts
* how to submit a PullRequest (description + screenshot of the result)

what do you think?

**Comment by borisrorsvort** [comment]
@toch yep. But how do you suggest we do this, knowing the differences we might have?

**Comment by toch** [comment]
I usually consider that the owner of the project is the one responsible to set that, or at least has a veto on that. In our case, it's @otagi. Considering the model hasn't been clearly stated from the beginning and the different opinions that have been already expressed, I have the feeling that it won't be satisfying. I don't want to enter a unlimited debate neither.

I see two options:

1. we go to an ownership model. we agree who owns the development of the website, and who owns content and communication
2. we go to a consensus model, we start from the style used by @otagi, we then submit what we agree and what we'd like to be changed, we do advocate once, then we vote if needed
