### ISSUE TITLE
Should we translate to french and dutch

### ISSUE THREAD

**Issue by borisrorsvort** [brug-be/rubybelgium#44]
I'm thinking that for SEO purposes it might be a good idea to translate all the pages that we have and propose a multilingual website.
I think we have enough resources in house to do this no?

@toch what d'ya think ?

**Comment by toch** [comment]
@borisrorsvort that for now, it's not a priority. everybody understands the English. Maintaining 3 langs is an overhead for now. IMHO

**Comment by borisrorsvort** [comment]
I kinda agree its overkill for now but if we want to enlarge our audience, we'll need this for sure.
Dont underestimate wallonian people to search in french in google ^^
So I'd keep an eye on this one. 
ps: Its not necessarily  a big maintenance since the content of the website is not changing hat much. Except for dynamic stuff

**Comment by toch** [comment]
let's try then. we'll see if we can keep up.
