### ISSUE TITLE
Build fail due to new js brug feature

### ISSUE THREAD

**Issue by borisrorsvort** [brug-be/rubybelgium#47]
I had no time to investigate yet but I think its related to the *erb on the brug.coffee script file that is somehow considered html
<img width="599" alt="screenshot 2016-05-16 00 00 32" src="https://cloud.githubusercontent.com/assets/39081/15277043/3b577eca-1af9-11e6-9030-7aa240832747.png">

**Comment by otagi** [comment]
Hm, strange. I never had that issue with sprockets in Rails projects.

Will look into it. Need sleep right now. 😪

**Comment by borisrorsvort** [comment]
Also why coffee script? Also the other script are normal js files.
Shall we keep it consistent and revert to normal js. Might also fix the build.

**Comment by otagi** [comment]
Because I miss (and love) ☕script.

**Comment by otagi** [comment]
Fixed by d373e91.
