### ISSUE TITLE
Adapt new home to the new personnas and pitch redux

### ISSUE THREAD

**Issue by borisrorsvort** [brug-be/rubybelgium#50]
- [x] lighter theme that can support more content (preview http://cobbler-alfonso-67104.bitballoon.com/)
- [x] rework content

**Comment by otagi** [comment]
I like the fresh new look!

Don't know if it can work, but what about alternating the section separation line rotations? (left, right, left, right)

**Comment by toch** [comment]
@borisrorsvort I like it very much. It's very clean.

The only thing I don't like is the non horizontal lines to break the sections. It feels like an unsuccessful attempt to create some natural organization. Something is missing.

Btw, on the contact section, there is like a glitch, part of the black is not hidden.
![screenshot from 2016-05-23 23-18-57](https://cloud.githubusercontent.com/assets/1059797/15484926/c73ac444-213c-11e6-9e2c-0c8607a8f707.png)

**Comment by borisrorsvort** [comment]
@toch Thanks! 

For the oblique separation I found them original and dynamic (aside from the glitch) but I guess this is all very personal. So suggest we focus more on the content strategy for now

**Comment by toch** [comment]
they are original, but they feel too regular to maintain the first feeling you got with the first one.

anyway :+1: to focus on content first
