### ISSUE TITLE
The question of staging

### ISSUE THREAD

**Issue by borisrorsvort** [brug-be/rubybelgium#51]
As the collaboration grows, the need to share a versions of the site in a specific branch becomes handy.
@ys proposed we use the heroku flows and the new static build pack for that.

@toch @otagi Thoughts?

**Comment by otagi** [comment]
Yes, 2 of them: 😺 
- Is it the right time, or is it premature? Do we already need to regularly test UI/UX from contributors?
- Do we just link GitHub with Heroku to auto-deploy the PRs? And keep using GH pages for production?

**Comment by toch** [comment]
@borisrorsvort 
I'm not sure to understand. Do you mean, that you would like to have automated deployment of changes submitted somewhere?

**Comment by borisrorsvort** [comment]
@toch not without test suite ;) What I'm saying is that is cool to be able to see PR changes live using heroku build apps. And then if we use heroku for that, why not hosting it there too. Nothing urgent or even critical. Just food for thoughts

**Comment by toch** [comment]
Which plan would you take then? just a free node?

**Comment by borisrorsvort** [comment]
Ok this is probably over engineered, people could just drop a build on something like https://www.bitballoon.com/ like I did the previous times. Probably should add a line in the readme about that. Closing this for now
