### ISSUE TITLE
Add a code of conduct page

### ISSUE THREAD

**Issue by borisrorsvort** [brug-be/rubybelgium#59]
Original document is https://github.com/brug-be/code_of_conduct
~~Maybe there is a way to add this to the website as a git submodule ?~~

**Comment by borisrorsvort** [comment]
@toch Any idea if we should use the submodule or just use the versionning of the site to track changes ?

**Comment by toch** [comment]
In my experience the submodule is not a flawless solution. I would go for a little script checking the sha and copy if newer.

**Comment by borisrorsvort** [comment]
@toch Ok then I suggest to just copy it for now as it doesnt often change.

**Comment by toch** [comment]
@borisrorsvort I wont mix the board about with the coc, I prefer it in a ad hoc page as @prayagb has suggested. What do you think?

I would move your other tasks in corresponding issues then.

**Comment by borisrorsvort** [comment]
Yep yep. I realized it was indeed better as a separate page. I've already answered him
