### ISSUE TITLE
Remove ambiguous bi-yearly usage

### ISSUE THREAD

**Issue by Bertg** [brug-be/rubybelgium#62]
In English "Bi-yearly" (and similar expressions) are ambiguous. It could mean twice a year, or every 2 years. So let's stop using it.

On the front page we use ```(Bi-)Yearly weekend gathering``` for Ruby Camp, So let's replace it. Some suggestions:

* Weekend gathering, twice a year
* One weekend, twice a year
* One weekend, once or twice a year
* One weekend, about twice a year

**Comment by borisrorsvort** [comment]
@Bertg Agreed, always found it ambiguous too. Lets change it. @otagi @toch What do you prefer ?

**Comment by otagi** [comment]
I like "One weekend, twice a year".

The first one is not clear if it's the whole weekend, or an afternoon during the weekend.

The last two imply doubt about the schedule. Let's be publicly assertive instead! 😉
