### ISSUE TITLE
Pseudo-dynamic Events section

### ISSUE THREAD

**Issue by radubogdan** [brug-be/rubybelgium#8]
The events section is entirely static => it'll require maintenance in the future and changes in the html files.

Possible solutions:

- **easy**: create a YML file that will store the data and the front-end serves it (it will require only changes in the yml file and a deploy to add a new event) 
- **fancy**: parse the meetup page and create them from meetup.
- **overwhelming** make a different app (sinatra perhaps) that will serve an iframe (Don't really like this)

I'll prototype the first solution this week and open a PR for you.

**Comment by otagi** [comment]
The easy solution is already there: https://github.com/brug-be/rubybelgium/blob/master/data/events.yml
;-)

(See also #9)

**Comment by radubogdan** [comment]
Oh my bad mate. For some reason I didn't find the yml file. I'll try to see how complicated is to fetch them directly from meetup, but meanwhile I think you can close this. 

Sorry ;)

**Comment by otagi** [comment]
No worries.
